import os

def get_plugins_data():
    """Return all plugin specifications"""
    plugins_items_dir = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "assets", "plugins", "plugins-items"))
    
    return [
        # System Tools
        {
            'id': 'bleachbit',
            'name': 'BleachBit',
            'desc': 'System cleaner to free disk space and guard your privacy.',
            'pkg': 'bleachbit',
            'cmd': 'bleachbit',
            'icon': os.path.join(plugins_items_dir, 'BleachBit.png'),
            'category': 'Cleaner',
        },
        {
            'id': 'timeshift',
            'name': 'Timeshift',
            'desc': 'System restore utility for Linux.',
            'pkg': 'timeshift',
            'cmd': 'timeshift-gtk',
            'icon': os.path.join(plugins_items_dir, 'timeshift.png'),
            'category': 'Backup',
        },
        {
            'id': 'baobab',
            'name': 'Disk Usage Analyzer',
            'desc': 'Visualize disk usage and identify large folders/files.',
            'pkg': 'baobab',
            'cmd': 'baobab',
            'icon': os.path.join(plugins_items_dir, 'diskusageanalyzer.png'),
            'category': 'Cleaner',
        },
        {
            'id': 'deja-dup',
            'name': 'Déjà Dup (Backups)',
            'desc': 'Simple backups for GNOME with cloud support.',
            'pkg': 'deja-dup',
            'cmd': 'deja-dup',
            'icon': os.path.join(plugins_items_dir, 'DejaDup.png'),
            'category': 'Backup',
        },
        {
            'id': 'gparted',
            'name': 'GParted',
            'desc': 'Partition editor for graphically managing disk partitions.',
            'pkg': 'gparted',
            'cmd': 'gparted',
            'icon': os.path.join(plugins_items_dir, 'gparted.jpeg'),
            'category': 'System',
        },
        {
            'id': 'gnome-disk-utility',
            'name': 'GNOME Disks',
            'desc': 'Manage disks and media — partition, format and benchmark.',
            'pkg': 'gnome-disk-utility',
            'cmd': 'gnome-disks',
            'icon': os.path.join(plugins_items_dir, 'gnomedisk.jpeg'),
            'category': 'System',
        },
        {
            'id': 'pavucontrol',
            'name': 'PulseAudio Volume Control',
            'desc': 'Advanced audio mixer for PulseAudio.',
            'pkg': 'pavucontrol',
            'cmd': 'pavucontrol',
            'icon': os.path.join(plugins_items_dir, 'pulseaudio.png'),
            'category': 'System',
        },
        {
            'id': 'system-config-printer',
            'name': 'Printers',
            'desc': 'Configure printers and manage print jobs.',
            'pkg': 'system-config-printer',
            'cmd': 'system-config-printer',
            'icon': os.path.join(plugins_items_dir, 'printers.png'),
            'category': 'System',
        },
        
        # System Monitoring
        {
            'id': 'btop',
            'name': 'btop',
            'desc': 'Modern resource monitor for CPU, memory, disks, network.',
            'pkg': 'btop',
            'cmd': 'btop',
            'icon': os.path.join(plugins_items_dir, 'btop.png'),
            'category': 'Monitor',
        },
        {
            'id': 'htop',
            'name': 'htop',
            'desc': 'Interactive process viewer and system monitor.',
            'pkg': 'htop',
            'cmd': 'htop',
            'icon': os.path.join(plugins_items_dir, 'htop.png'),
            'category': 'Monitor',
        },
        {
            'id': 'gnome-system-monitor',
            'name': 'GNOME System Monitor',
            'desc': 'Graphical system monitor for processes and resources.',
            'pkg': 'gnome-system-monitor',
            'cmd': 'gnome-system-monitor',
            'icon': os.path.join(plugins_items_dir, 'gnomesystem.jpeg'),
            'category': 'Monitor',
        },
        
        # GPU Tools
        {
            'id': 'nvidia-settings',
            'name': 'NVIDIA Settings',
            'desc': 'Configure NVIDIA drivers and GPU options.',
            'pkg': 'nvidia-settings',
            'cmd': 'nvidia-settings',
            'icon': os.path.join(plugins_items_dir, 'nvideasettings.jpeg'),
            'category': 'GPU',
        },
        {
            'id': 'nvtop',
            'name': 'nvtop',
            'desc': 'NVIDIA/AMD Intel GPU process monitor (requires supported GPU).',
            'pkg': 'nvtop',
            'cmd': 'nvtop',
            'icon': os.path.join(plugins_items_dir, 'nvtop.png'),
            'category': 'GPU',
        },
        
        # Utilities
        {
            'id': 'simple-scan',
            'name': 'Document Scanner',
            'desc': 'Scan documents and photos with a simple interface.',
            'pkg': 'simple-scan',
            'cmd': 'simple-scan',
            'icon': os.path.join(plugins_items_dir, 'documentscanner.png'),
            'category': 'Utility',
        },
        {
            'id': 'file-roller',
            'name': 'Archive Manager',
            'desc': 'Create and extract archives (zip, tar, etc.).',
            'pkg': 'file-roller',
            'cmd': 'file-roller',
            'icon': os.path.join(plugins_items_dir, 'achive.png'),
            'category': 'Utility',
        },
        {
            'id': 'calibre',
            'name': 'Calibre',
            'desc': 'Powerful and easy to use e-book manager.',
            'pkg': 'calibre',
            'cmd': 'calibre',
            'icon': os.path.join(plugins_items_dir, 'calibre.png'),
            'category': 'Utility',
        },
        
        # Multimedia
        {
            'id': 'vlc',
            'name': 'VLC Media Player',
            'desc': 'Universal multimedia player for all formats.',
            'pkg': 'vlc',
            'cmd': 'vlc',
            'icon': os.path.join(plugins_items_dir, 'vlc.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'audacity',
            'name': 'Audacity',
            'desc': 'Free audio editor and recorder for all platforms.',
            'pkg': 'audacity',
            'cmd': 'audacity',
            'icon': os.path.join(plugins_items_dir, 'audacity.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'obs-studio',
            'name': 'OBS Studio',
            'desc': 'Free and open source software for video recording.',
            'pkg': 'obs-studio',
            'cmd': 'obs',
            'icon': os.path.join(plugins_items_dir, 'obs.png'),
            'category': 'Multimedia',
        },
        
        # Graphics
        {
            'id': 'gimp',
            'name': 'GIMP',
            'desc': 'GNU Image Manipulation Program for photo editing.',
            'pkg': 'gimp',
            'cmd': 'gimp',
            'icon': os.path.join(plugins_items_dir, 'gimp.png'),
            'category': 'Graphics',
        },
        {
            'id': 'blender',
            'name': 'Blender',
            'desc': '3D modeling, animation, and rendering software.',
            'pkg': 'blender',
            'cmd': 'blender',
            'icon': os.path.join(plugins_items_dir, 'blender.png'),
            'category': 'Graphics',
        },
        
        # Internet & Communication
        {
            'id': 'thunderbird',
            'name': 'Thunderbird',
            'desc': 'Free email client and news reader.',
            'pkg': 'thunderbird',
            'cmd': 'thunderbird',
            'icon': os.path.join(plugins_items_dir, 'thunderbird.png'),
            'category': 'Internet',
        },
        {
            'id': 'transmission',
            'name': 'Transmission',
            'desc': 'Fast, easy, and free BitTorrent client.',
            'pkg': 'transmission-gtk',
            'cmd': 'transmission-gtk',
            'icon': os.path.join(plugins_items_dir, 'transmission.png'),
            'category': 'Internet',
        },
        {
            'id': 'qbittorrent',
            'name': 'qBittorrent',
            'desc': 'Open source BitTorrent client written in C++.',
            'pkg': 'qbittorrent',
            'cmd': 'qbittorrent',
            'icon': os.path.join(plugins_items_dir, 'qbittorrent.png'),
            'category': 'Internet',
        },
        
        # Development Tools
        {
            'id': 'code',
            'name': 'Visual Studio Code',
            'desc': 'Powerful source code editor with IntelliSense and debugging.',
            'pkg': 'code',
            'cmd': 'code',
            'icon': os.path.join(plugins_items_dir, 'vscode.png'),
            'category': 'Development',
        },
        {
            'id': 'git',
            'name': 'Git',
            'desc': 'Distributed version control system for tracking changes.',
            'pkg': 'git',
            'cmd': 'git',
            'icon': os.path.join(plugins_items_dir, 'git.png'),
            'category': 'Development',
        },
        {
            'id': 'nodejs',
            'name': 'Node.js',
            'desc': 'JavaScript runtime built on Chrome\'s V8 JavaScript engine.',
            'pkg': 'nodejs',
            'cmd': 'node',
            'icon': os.path.join(plugins_items_dir, 'nodejs.png'),
            'category': 'Development',
        },
        {
            'id': 'python',
            'name': 'Python',
            'desc': 'High-level programming language for general-purpose programming.',
            'pkg': 'python',
            'cmd': 'python',
            'icon': os.path.join(plugins_items_dir, 'python.png'),
            'category': 'Development',
        },
        
        # Office & Productivity
        {
            'id': 'libreoffice',
            'name': 'LibreOffice',
            'desc': 'Free and open-source office productivity software suite.',
            'pkg': 'libreoffice-fresh',
            'cmd': 'libreoffice',
            'icon': os.path.join(plugins_items_dir, 'libreoffice.png'),
            'category': 'Office',
        },
        {
            'id': 'onlyoffice',
            'name': 'OnlyOffice',
            'desc': 'Complete office suite with document, spreadsheet and presentation editors.',
            'pkg': 'onlyoffice-bin',
            'cmd': 'onlyoffice-desktopeditors',
            'icon': os.path.join(plugins_items_dir, 'onlyoffice.png'),
            'category': 'Office',
        },
        {
            'id': 'notion',
            'name': 'Notion',
            'desc': 'All-in-one workspace for notes, tasks, wikis, and databases.',
            'pkg': 'notion-app',
            'cmd': 'notion-app',
            'icon': os.path.join(plugins_items_dir, 'notion.png'),
            'category': 'Office',
        },
        
        # Games
        {
            'id': 'steam',
            'name': 'Steam',
            'desc': 'Digital distribution platform for PC gaming.',
            'pkg': 'steam',
            'cmd': 'steam',
            'icon': os.path.join(plugins_items_dir, 'steam.png'),
            'category': 'Games',
        },
        {
            'id': 'lutris',
            'name': 'Lutris',
            'desc': 'Gaming platform for Linux with Wine and Proton support.',
            'pkg': 'lutris',
            'cmd': 'lutris',
            'icon': os.path.join(plugins_items_dir, 'lutris.png'),
            'category': 'Games',
        },
        {
            'id': 'heroic',
            'name': 'Heroic Games Launcher',
            'desc': 'Native GOG, Epic Games and Amazon Prime Games launcher.',
            'pkg': 'heroic-games-launcher-bin',
            'cmd': 'heroic',
            'icon': os.path.join(plugins_items_dir, 'heroic.png'),
            'category': 'Games',
        },
        
        # Security & Privacy
        {
            'id': 'keepassxc',
            'name': 'KeePassXC',
            'desc': 'Cross-platform community-driven port of KeePass password manager.',
            'pkg': 'keepassxc',
            'cmd': 'keepassxc',
            'icon': os.path.join(plugins_items_dir, 'keepassxc.png'),
            'category': 'Security',
        },
        {
            'id': 'bitwarden',
            'name': 'Bitwarden',
            'desc': 'Secure and free password manager for all of your devices.',
            'pkg': 'bitwarden',
            'cmd': 'bitwarden',
            'icon': os.path.join(plugins_items_dir, 'bitwarden.png'),
            'category': 'Security',
        },
        {
            'id': 'tor-browser',
            'name': 'Tor Browser',
            'desc': 'Private web browser that protects your anonymity.',
            'pkg': 'tor-browser',
            'cmd': 'tor-browser',
            'icon': os.path.join(plugins_items_dir, 'tor.png'),
            'category': 'Security',
        },
        
        # Communication
        {
            'id': 'discord',
            'name': 'Discord',
            'desc': 'Voice, video and text chat app for communities and friends.',
            'pkg': 'discord',
            'cmd': 'discord',
            'icon': os.path.join(plugins_items_dir, 'discord.png'),
            'category': 'Communication',
        },
        {
            'id': 'telegram',
            'name': 'Telegram Desktop',
            'desc': 'Fast and secure desktop messaging app.',
            'pkg': 'telegram-desktop',
            'cmd': 'telegram-desktop',
            'icon': os.path.join(plugins_items_dir, 'telegram.png'),
            'category': 'Communication',
        },
        {
            'id': 'signal',
            'name': 'Signal',
            'desc': 'Private messenger with end-to-end encryption.',
            'pkg': 'signal-desktop',
            'cmd': 'signal-desktop',
            'icon': os.path.join(plugins_items_dir, 'signal.png'),
            'category': 'Communication',
        },
        {
            'id': 'zoom',
            'name': 'Zoom',
            'desc': 'Video conferencing and web conferencing service.',
            'pkg': 'zoom',
            'cmd': 'zoom',
            'icon': os.path.join(plugins_items_dir, 'zoom.png'),
            'category': 'Communication',
        },
        
        # Education & Learning
        {
            'id': 'anki',
            'name': 'Anki',
            'desc': 'Powerful, intelligent flash cards for effective learning.',
            'pkg': 'anki',
            'cmd': 'anki',
            'icon': os.path.join(plugins_items_dir, 'anki.png'),
            'category': 'Education',
        },
        {
            'id': 'geogebra',
            'name': 'GeoGebra',
            'desc': 'Dynamic mathematics software for all levels of education.',
            'pkg': 'geogebra',
            'cmd': 'geogebra',
            'icon': os.path.join(plugins_items_dir, 'geogebra.png'),
            'category': 'Education',
        },
        
        # Customization
        {
            'id': 'latte-dock',
            'name': 'Latte Dock',
            'desc': 'Dock based on Plasma frameworks for an elegant desktop.',
            'pkg': 'latte-dock',
            'cmd': 'latte-dock',
            'icon': os.path.join(plugins_items_dir, 'latte.png'),
            'category': 'Customization',
        },
        {
            'id': 'conky',
            'name': 'Conky',
            'desc': 'Light-weight system monitor for X windows.',
            'pkg': 'conky',
            'cmd': 'conky',
            'icon': os.path.join(plugins_items_dir, 'conky.png'),
            'category': 'Customization',
        },
        {
            'id': 'neofetch',
            'name': 'Neofetch',
            'desc': 'Command-line system information tool with ASCII art.',
            'pkg': 'neofetch',
            'cmd': 'neofetch',
            'icon': os.path.join(plugins_items_dir, 'neofetch.png'),
            'category': 'Customization',
        },
        {
            'id': 'polybar',
            'name': 'Polybar',
            'desc': 'Fast and easy-to-use status bar for tiling window managers.',
            'pkg': 'polybar',
            'cmd': 'polybar',
            'icon': os.path.join(plugins_items_dir, 'polybar.png'),
            'category': 'Customization',
        },
        
        # Web Browsers
        {
            'id': 'firefox',
            'name': 'Firefox',
            'desc': 'Fast, private & safe web browser from Mozilla.',
            'pkg': 'firefox',
            'cmd': 'firefox',
            'icon': os.path.join(plugins_items_dir, 'firefox.png'),
            'category': 'Internet',
        },
        {
            'id': 'chromium',
            'name': 'Chromium',
            'desc': 'Open-source web browser project from Google.',
            'pkg': 'chromium',
            'cmd': 'chromium',
            'icon': os.path.join(plugins_items_dir, 'chromium.png'),
            'category': 'Internet',
        },
        {
            'id': 'brave',
            'name': 'Brave Browser',
            'desc': 'Privacy-focused web browser with built-in ad blocker.',
            'pkg': 'brave-bin',
            'cmd': 'brave',
            'icon': os.path.join(plugins_items_dir, 'brave.png'),
            'category': 'Internet',
        },
        {
            'id': 'opera',
            'name': 'Opera',
            'desc': 'Fast, secure, easy-to-use browser with built-in VPN.',
            'pkg': 'opera',
            'cmd': 'opera',
            'icon': os.path.join(plugins_items_dir, 'opera.png'),
            'category': 'Internet',
        },
        
        # Text Editors & IDEs
        {
            'id': 'vim',
            'name': 'Vim',
            'desc': 'Highly configurable text editor built to enable efficient text editing.',
            'pkg': 'vim',
            'cmd': 'vim',
            'icon': os.path.join(plugins_items_dir, 'vim.png'),
            'category': 'Development',
        },
        {
            'id': 'neovim',
            'name': 'Neovim',
            'desc': 'Hyperextensible Vim-based text editor.',
            'pkg': 'neovim',
            'cmd': 'nvim',
            'icon': os.path.join(plugins_items_dir, 'neovim.png'),
            'category': 'Development',
        },
        {
            'id': 'sublime-text',
            'name': 'Sublime Text',
            'desc': 'Sophisticated text editor for code, markup and prose.',
            'pkg': 'sublime-text-4',
            'cmd': 'subl',
            'icon': os.path.join(plugins_items_dir, 'sublime.png'),
            'category': 'Development',
        },
        {
            'id': 'atom',
            'name': 'Atom',
            'desc': 'Hackable text editor for the 21st Century.',
            'pkg': 'atom',
            'cmd': 'atom',
            'icon': os.path.join(plugins_items_dir, 'atom.png'),
            'category': 'Development',
        },
        {
            'id': 'intellij-idea',
            'name': 'IntelliJ IDEA',
            'desc': 'Powerful IDE for Java and other JVM languages.',
            'pkg': 'intellij-idea-community-edition',
            'cmd': 'idea',
            'icon': os.path.join(plugins_items_dir, 'intellij.png'),
            'category': 'Development',
        },
        
        # Media & Entertainment
        {
            'id': 'spotify',
            'name': 'Spotify',
            'desc': 'Digital music streaming service with millions of songs.',
            'pkg': 'spotify',
            'cmd': 'spotify',
            'icon': os.path.join(plugins_items_dir, 'spotify.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'mpv',
            'name': 'MPV',
            'desc': 'Free, open source, and cross-platform media player.',
            'pkg': 'mpv',
            'cmd': 'mpv',
            'icon': os.path.join(plugins_items_dir, 'mpv.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'kdenlive',
            'name': 'Kdenlive',
            'desc': 'Free and open-source video editing software.',
            'pkg': 'kdenlive',
            'cmd': 'kdenlive',
            'icon': os.path.join(plugins_items_dir, 'kdenlive.png'),
            'category': 'Multimedia',
        },
        {
            'id': 'handbrake',
            'name': 'HandBrake',
            'desc': 'Open-source video transcoder for converting video files.',
            'pkg': 'handbrake',
            'cmd': 'ghb',
            'icon': os.path.join(plugins_items_dir, 'handbrake.png'),
            'category': 'Multimedia',
        },
        
        # Graphics & Design
        {
            'id': 'inkscape',
            'name': 'Inkscape',
            'desc': 'Professional vector graphics editor for creating scalable graphics.',
            'pkg': 'inkscape',
            'cmd': 'inkscape',
            'icon': os.path.join(plugins_items_dir, 'inkscape.png'),
            'category': 'Graphics',
        },
        {
            'id': 'krita',
            'name': 'Krita',
            'desc': 'Professional FREE and open source painting program.',
            'pkg': 'krita',
            'cmd': 'krita',
            'icon': os.path.join(plugins_items_dir, 'krita.png'),
            'category': 'Graphics',
        },
        {
            'id': 'darktable',
            'name': 'Darktable',
            'desc': 'Open source photography workflow application and RAW developer.',
            'pkg': 'darktable',
            'cmd': 'darktable',
            'icon': os.path.join(plugins_items_dir, 'darktable.png'),
            'category': 'Graphics',
        },
        {
            'id': 'rawtherapee',
            'name': 'RawTherapee',
            'desc': 'Powerful cross-platform raw photo processing program.',
            'pkg': 'rawtherapee',
            'cmd': 'rawtherapee',
            'icon': os.path.join(plugins_items_dir, 'rawtherapee.png'),
            'category': 'Graphics',
        },
        
        # File Management
        {
            'id': 'nautilus',
            'name': 'Nautilus',
            'desc': 'GNOME file manager with clean and simple interface.',
            'pkg': 'nautilus',
            'cmd': 'nautilus',
            'icon': os.path.join(plugins_items_dir, 'nautilus.png'),
            'category': 'Utility',
        },
        {
            'id': 'thunar',
            'name': 'Thunar',
            'desc': 'Fast and easy to use file manager for Xfce desktop.',
            'pkg': 'thunar',
            'cmd': 'thunar',
            'icon': os.path.join(plugins_items_dir, 'thunar.png'),
            'category': 'Utility',
        },
        {
            'id': 'ranger',
            'name': 'Ranger',
            'desc': 'Console file manager with VI key bindings.',
            'pkg': 'ranger',
            'cmd': 'ranger',
            'icon': os.path.join(plugins_items_dir, 'ranger.png'),
            'category': 'Utility',
        },
        
        # Terminal Emulators
        {
            'id': 'kitty',
            'name': 'Kitty',
            'desc': 'Fast, feature-rich, GPU based terminal emulator.',
            'pkg': 'kitty',
            'cmd': 'kitty',
            'icon': os.path.join(plugins_items_dir, 'kitty.png'),
            'category': 'System',
        },
        {
            'id': 'alacritty',
            'name': 'Alacritty',
            'desc': 'Cross-platform, GPU-accelerated terminal emulator.',
            'pkg': 'alacritty',
            'cmd': 'alacritty',
            'icon': os.path.join(plugins_items_dir, 'alacritty.png'),
            'category': 'System',
        },
        {
            'id': 'terminator',
            'name': 'Terminator',
            'desc': 'Terminal emulator with support for multiple terminals in one window.',
            'pkg': 'terminator',
            'cmd': 'terminator',
            'icon': os.path.join(plugins_items_dir, 'terminator.png'),
            'category': 'System',
        },
        
        # Productivity & Notes
        {
            'id': 'obsidian',
            'name': 'Obsidian',
            'desc': 'Powerful knowledge base that works on top of local folder of plain text files.',
            'pkg': 'obsidian',
            'cmd': 'obsidian',
            'icon': os.path.join(plugins_items_dir, 'obsidian.png'),
            'category': 'Office',
        },
        {
            'id': 'joplin',
            'name': 'Joplin',
            'desc': 'Free, open source note taking and to-do application.',
            'pkg': 'joplin-appimage',
            'cmd': 'joplin',
            'icon': os.path.join(plugins_items_dir, 'joplin.png'),
            'category': 'Office',
        },
        {
            'id': 'typora',
            'name': 'Typora',
            'desc': 'Minimal markdown editor with live preview.',
            'pkg': 'typora',
            'cmd': 'typora',
            'icon': os.path.join(plugins_items_dir, 'typora.png'),
            'category': 'Office',
        },
        
        # Virtualization
        {
            'id': 'virtualbox',
            'name': 'VirtualBox',
            'desc': 'Powerful x86 and AMD64/Intel64 virtualization product.',
            'pkg': 'virtualbox',
            'cmd': 'virtualbox',
            'icon': os.path.join(plugins_items_dir, 'virtualbox.png'),
            'category': 'System',
        },
        {
            'id': 'qemu',
            'name': 'QEMU',
            'desc': 'Generic and open source machine emulator and virtualizer.',
            'pkg': 'qemu-full',
            'cmd': 'qemu-system-x86_64',
            'icon': os.path.join(plugins_items_dir, 'qemu.png'),
            'category': 'System',
        },
        
        # Network Tools
        {
            'id': 'wireshark',
            'name': 'Wireshark',
            'desc': 'Network protocol analyzer for troubleshooting and analysis.',
            'pkg': 'wireshark-qt',
            'cmd': 'wireshark',
            'icon': os.path.join(plugins_items_dir, 'wireshark.png'),
            'category': 'Security',
        },
        {
            'id': 'nmap',
            'name': 'Nmap',
            'desc': 'Network discovery and security auditing utility.',
            'pkg': 'nmap',
            'cmd': 'nmap',
            'icon': os.path.join(plugins_items_dir, 'nmap.png'),
            'category': 'Security',
        },
        
        # More Games
        {
            'id': 'minecraft',
            'name': 'Minecraft Launcher',
            'desc': 'Official launcher for the popular sandbox game.',
            'pkg': 'minecraft-launcher',
            'cmd': 'minecraft-launcher',
            'icon': os.path.join(plugins_items_dir, 'minecraft.png'),
            'category': 'Games',
        },
        {
            'id': 'retroarch',
            'name': 'RetroArch',
            'desc': 'Frontend for emulators, game engines and media players.',
            'pkg': 'retroarch',
            'cmd': 'retroarch',
            'icon': os.path.join(plugins_items_dir, 'retroarch.png'),
            'category': 'Games',
        },
        
        # Database Tools
        {
            'id': 'dbeaver',
            'name': 'DBeaver',
            'desc': 'Universal database tool for developers and database administrators.',
            'pkg': 'dbeaver',
            'cmd': 'dbeaver',
            'icon': os.path.join(plugins_items_dir, 'dbeaver.png'),
            'category': 'Development',
        },
        
        # More Education
        {
            'id': 'stellarium',
            'name': 'Stellarium',
            'desc': 'Free open source planetarium for your computer.',
            'pkg': 'stellarium',
            'cmd': 'stellarium',
            'icon': os.path.join(plugins_items_dir, 'stellarium.png'),
            'category': 'Education',
        },
        {
            'id': 'kstars',
            'name': 'KStars',
            'desc': 'Desktop planetarium showing accurate night sky simulation.',
            'pkg': 'kstars',
            'cmd': 'kstars',
            'icon': os.path.join(plugins_items_dir, 'kstars.png'),
            'category': 'Education',
        },
    ]
